app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/', 'WelcomeController@index');
Route::get('home', 'HomeController@index');

Route::post('users', ['as' => 'users.store', 'uses' => 'UsersController@store']);
Route::get('users', ['as' => 'users.index', 'uses' => 'UsersController@index']);
Route::get('users/create', ['as' => 'users.create', 'uses' => 'UsersController@create']);
Route::get('users/archived', ['as' => 'users.archived', 'uses' => 'UsersController@archived']);
Route::delete('users/{user}', ['as' => 'users.delete', 'uses' => 'UsersController@delete']);
Route::get('users/{user}', ['as' => 'users.show', 'uses' => 'UsersController@show']);
Route::put('users/{user}', ['as' => 'users.update', 'uses' => 'UsersController@update']);
Route::patch('users/{user}', ['as' => 'users.update', 'uses' => 'UsersController@update']);
Route::get('users/{user}/edit', ['as' => 'users.edit', 'uses' => 'UsersController@edit']);
Route::patch('users/{user}/restore', ['as' => 'users.restore', 'uses' => 'UsersController@restore']);

Route::post('leagues', ['as' => 'leagues.store', 'uses' => 'LeaguesController@store']);
Route::get('leagues', ['as' => 'leagues.index', 'uses' => 'LeaguesController@index']);
Route::get('leagues/create', ['as' => 'leagues.create', 'uses' => 'LeaguesController@create']);
Route::get('leagues/archived', ['as' => 'leagues.archived', 'uses' => 'LeaguesController@archived']);
Route::delete('leagues/{league}', ['as' => 'leagues.delete', 'uses' => 'LeaguesController@delete']);
Route::get('leagues/{league}', ['as' => 'leagues.show', 'uses' => 'LeaguesController@show']);
Route::put('leagues/{league}', ['as' => 'leagues.update', 'uses' => 'LeaguesController@update']);
Route::patch('leagues/{league}', ['as' => 'leagues.update', 'uses' => 'LeaguesController@update']);
Route::get('leagues/{league}/edit', ['as' => 'leagues.edit', 'uses' => 'LeaguesController@edit']);
Route::patch('leagues/{league}/restore', ['as' => 'leagues.restore', 'uses' => 'LeaguesController@restore']);

Route::post('leagues/{league}/charters', ['as' => 'leagues.charters.store', 'uses' => 'ChartersController@store']);
Route::get('leagues/{league}/charters/create', ['as' => 'leagues.charters.create', 'uses' => 'ChartersController@create']);
Route::delete('leagues/{league}/charters/{charter}', ['as' => 'leagues.charters.delete', 'uses' => 'ChartersController@delete']);
Route::get('leagues/{league}/charters/{charter}', ['as' => 'leagues.charters.show', 'uses' => 'ChartersController@show']);
Route::put('leagues/{league}/charters/{charter}', ['as' => 'leagues.charters.update', 'uses' => 'ChartersController@update']);
Route::patch('leagues/{league}/charters/{charter}', ['as' => 'leagues.charters.update', 'uses' => 'ChartersController@update']);
Route::get('leagues/{league}/charters/{charter}/edit', ['as' => 'leagues.charters.edit', 'uses' => 'ChartersController@edit']);
Route::patch('leagues/{league}/charters/{charter}/request-approval', ['as' => 'leagues.charters.request_approval', 'uses' => 'ChartersController@requestApproval']);
Route::patch('leagues/{league}/charters/{charter}/approve', ['as' => 'leagues.charters.approve', 'uses' => 'ChartersController@approve']);
Route::patch('leagues/{league}/charters/{charter}/reject', ['as' => 'leagues.charters.reject', 'uses' => 'ChartersController@reject']);

Route::resource('events', 'EventsController');

Route::controllers([
  'auth'     => 'Auth\AuthController',
  'password' => 'Auth\PasswordController',
]);

Route::get('clear-cache', function(){
  $instructions = ['auth:clear-resets', 'cache:clear', 'config:clear', 'clear-compiled', 'view:clear', 'config:cache', 'optimize'];
  $results = [];
  foreach( $instructions as $instruction )
  {
    $results[ $instruction ] = Artisan::call( $instruction );
  }
  printf('<pre>%s</pre>', var_export( $results, 1 ) );
  die;
});

Route::get('migrate', function(){
  $result = Artisan::call('migrate');
  printf('<pre>%s</pre>', var_export( $result, 1 ) );
  die;
});

// Role-based permissions
Entrust::routeNeedsPermission('home', 'home');

Entrust::routeNeedsPermission('users*', 'user-show');
Entrust::routeNeedsPermission('users/create', 'user-create');
Entrust::routeNeedsPermission('users/store', 'user-create');
Entrust::routeNeedsPermission('users/*/edit', 'user-edit');
Entrust::routeNeedsPermission('users/*/update', 'user-edit');
Entrust::routeNeedsPermission('users/*/delete', 'user-delete');
Entrust::routeNeedsPermission('users/*/restore', 'user-create');

Entrust::routeNeedsPermission('leagues*', 'league-show');
Entrust::routeNeedsPermission('leagues/create', 'league-create');
Entrust::routeNeedsPermission('leagues/store', 'league-create');
Entrust::routeNeedsPermission('leagues/*/edit', 'league-edit');
Entrust::routeNeedsPermission('leagues/*/update', 'league-edit');
Entrust::routeNeedsPermission('leagues/*/delete', 'league-delete');
Entrust::routeNeedsPermission('leagues/*/restore', 'league-create');

Entrust::routeNeedsPermission('leagues/*/charters*', 'charter-show');
Entrust::routeNeedsPermission('leagues/*/charters/create', 'charter-create');
Entrust::routeNeedsPermission('leagues/*/charters/store', 'charter-create');
Entrust::routeNeedsPermission('leagues/*/charters/*/edit', 'charter-edit');
Entrust::routeNeedsPermission('leagues/*/charters/*/update', 'charter-edit');
Entrust::routeNeedsPermission('leagues/*/charters/*/delete', 'charter-delete');
Entrust::routeNeedsPermission('leagues/*/charters/*/request-approval', 'charter-request_approval');
Entrust::routeNeedsPermission('leagues/*/charters/*/approve', 'charter-approve');
Entrust::routeNeedsPermission('leagues/*/charters/*/reject', 'charter-reject');

Entrust::routeNeedsPermission('events*', 'event-show');

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Muster</title>

    <link href="{{ asset('/css/bootstrap.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('/css/bootstrap-theme.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('/css/fonts.css') }}" rel="stylesheet" />
    <link href="{{ asset('/css/app.css') }}" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body role="document">
    @if( !Auth::guest() )
      <nav class="navbar navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Muster</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              @if( Auth::user()->can('league-show') )
                <li><a href="{{ route('leagues.index') }}">Leagues</a></li>
              @endif
              @if( Auth::user()->can('user-show') )
                <li><a href="{{ route('users.index') }}">Users</a></li>
              @endif
              @if( Auth::user()->can('event-show') )
                <li><a href="{{ route('events.index') }}">Audit Log</a></li>
              @endif
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{{ url('/auth/password-change') }}">Change Password</a></li>
                    <li><a href="{{ url('/auth/logout') }}">Logout</a></li>
                  </ul>
                </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
    @endif

    <div class="container" role="main">
      @if( Session::has('message') )
        <div class="flash alert-info">
          <p>{{ Session::get('message') }}</p>
        </div>
      @endif

      @if( $errors->any() || Session::has('error') )
        <div class='flash alert-danger'>
          @foreach( $errors->all() as $error )
            <p>{{ $error }}</p>
          @endforeach
          @if( Session::has('error') )
            <p>{{ Session::get('error') }}</p>
          @endif
        </div>
      @endif

      @yield('content')
    </div>
    @if( !Auth::guest() )
    <br />
    <footer class="navbar-fixed-bottom">
      <h3><a href="http://ukrda.org.uk/" target="_blank">United Kingdom Roller Derby Association</a></h3>
    </footer>
    @endif
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-66916661-5', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>

resources/views/home.blade.php
@extends('app')

@section('content')
  <div class="page-header">
    <h1>All leagues</h1>
  </div>

  @if( !$leagues->count() )
    <p>None found!</p>
  @else
    <table class="table table-striped">
      <thead>
        <tr>
          <th rowspan="2">League</th>
          <th rowspan="2" style="border-right: 2px solid #ddd">User</th>
          <th colspan="{{ count( $charter_types ) }}" style="text-align: center; border-bottom: 1px solid #ddd;">Current Charters</th>
        </tr>
        <tr>
          @foreach( $charter_types as $type )
            <th>{{ $type->name }}</th>
          @endforeach
        </tr>
      </thead>
      <tbody>
        @foreach( $leagues as $league )
          <tr>
            <td><a href="{{ route('leagues.show', [ $league->slug ] ) }}">{{ $league->name }}</a></td>
            <td style="border-right: 2px solid #ddd;">
              @if( $user = $league->user )
                <a href="{{ route('users.show', [ $league->user->id ] ) }}">{{ $user->name }}</a>
              @else
                -
              @endif
            </td>
            @foreach( $charter_types as $type )
            <td>
              @if( $charter = $league->currentCharter( $type->id ) )
                <a href="{{ route('leagues.charters.show', [ $league->slug, $charter->slug ] ) }}">{{ $charter->name }}</a>
              @else
                -
              @endif
            </td>
            @endforeach
          </tr>
        @endforeach
      </tbody>
    </table>
  @endif
@endsection